[package]
name = "rust-auto-reorder-cli"
version = "0.1.0"
edition = "2024"
description = "CLI for reordering and linting Rust source code. Intended for LLM use."
repository = "https://github.com/Sewer56/rust-auto-reorder"
license = "Apache-2.0"
readme = "README.MD"
# keywords (search terms): https://crates.io/keywords
keywords = ["cli", "rust", "rustfmt", "reorder", "lint"]
# categories (fixed list): https://crates.io/categories
categories = ["command-line-utilities"]

[[bin]]
name = "rust-auto-reorder"
path = "src/main.rs"

[dependencies]
rust-auto-reorder = { path = "../rust-auto-reorder", version = "0.1.0" }
rust-doc-check = { path = "../doc-check", version = "0.1.0" }
rust-source-model = { path = "../rust-source-model", version = "0.1.0" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
proc-macro2 = { version = "1", features = ["span-locations"] }

[dev-dependencies]
