//! Curated shorter wording for TEXT006 hints, including removable framing.

/// Lowercase wording mapped to display-ready alternatives or deletion guidance.
///
/// Entries are sorted by wording so the scanner can select an initial-letter
/// range. List inflections explicitly; do not infer stems or technical meanings.
pub(super) const SUGGESTIONS: &[(&str, &str)] = &[
    ("a considerable amount of", "`much` or `a lot of`"),
    ("a considerable number of", "`many`"),
    ("a large amount of", "`much` or `a lot of`"),
    ("a large number of", "`many`"),
    ("a majority of", "`most`"),
    ("a small number of", "`few`"),
    ("absolutely essential", "`essential`"),
    ("absolutely necessary", "`necessary`"),
    ("accomplish", "`do` or `achieve`"),
    ("accordingly", "`so`"),
    ("additional", "`more` or `extra`"),
    ("additionally", "`also`"),
    ("aforementioned", "name the thing, or use `this` or `that`"),
    ("all of the", "`all the`"),
    ("along the lines of", "`like`"),
    ("an abundance of", "`plenty of`"),
    ("an adequate number of", "`enough`"),
    ("approximately", "`about`"),
    ("as a consequence of", "`because of`"),
    (
        "as a matter of fact",
        "omit this framing, or use `in fact` for contrast",
    ),
    ("as a means of", "`to` or `by`; adjust the following verb"),
    ("as a result of", "`because of`"),
    ("as a result of the fact that", "`because`"),
    ("as an example", "`for example`"),
    ("as can be seen", "state what the evidence shows directly"),
    ("as is the case with", "`like`"),
    (
        "as previously mentioned",
        "omit this reminder, or link to the earlier point",
    ),
    (
        "as previously stated",
        "omit this reminder, or link to the earlier point",
    ),
    (
        "as such",
        "`so` if this means a result; retain it if it means `in that role`",
    ),
    ("as to whether", "`whether`"),
    ("ascertain", "`find out` or `check`"),
    ("assist", "`help`"),
    ("assistance", "`help`"),
    ("at a later date", "`later`"),
    ("at all times", "`always`"),
    ("at an earlier point in time", "`earlier`"),
    ("at the present moment", "`now`"),
    ("at the present time", "`now`"),
    ("at this juncture", "`now`"),
    ("at this moment in time", "`now`"),
    ("at this point in time", "`now`"),
    ("be advised that", "state the notice directly"),
    ("because of the fact that", "`because`"),
    ("by means of", "`by` or `with`"),
    ("by virtue of the fact that", "`because`"),
    (
        "capability",
        "`ability` when no technical meaning is intended",
    ),
    ("close proximity", "`proximity`, or rewrite with `near`"),
    ("commence", "`start` or `begin`"),
    ("commenced", "`started` or `began`"),
    ("commencement", "`start` or `beginning`"),
    ("commences", "`starts` or `begins`"),
    ("commencing", "`starting` or `beginning`"),
    ("completely eliminate", "`eliminate`"),
    ("concerning", "`about` when used as a preposition"),
    ("consequently", "`so`"),
    ("constitutes", "`is` or `forms`"),
    ("currently in progress", "`in progress`"),
    (
        "demonstrate",
        "`show` unless a specific demonstration is meant",
    ),
    ("demonstrated", "`showed` or `shown`, depending on grammar"),
    ("demonstrates", "`shows`"),
    ("demonstrating", "`showing`"),
    ("despite the fact that", "`although`"),
    ("due to the fact that", "`because`"),
    ("during the course of", "`during`"),
    ("during the time that", "`while`"),
    ("each and every", "`each` or `every`"),
    ("elucidate", "`explain` or `clarify`"),
    ("endeavor", "`try` or `attempt`"),
    ("endeavored", "`tried` or `attempted`"),
    ("endeavoring", "`trying` or `attempting`"),
    ("endeavors", "`tries` or `attempts`"),
    ("endeavour", "`try` or `attempt`"),
    ("endeavoured", "`tried` or `attempted`"),
    ("endeavouring", "`trying` or `attempting`"),
    ("endeavours", "`tries` or `attempts`"),
    ("equally as", "`equally` or `as`"),
    ("establish the identity of", "`identify`"),
    ("every single", "`every`"),
    ("facilitate", "`help` or `make easier`"),
    ("facilitated", "`helped` or `made easier`"),
    ("facilitates", "`helps` or `makes easier`"),
    ("facilitating", "`helping` or `making easier`"),
    ("fewer in number", "`fewer`"),
    ("first and foremost", "`first`"),
    ("for a period of", "`for`"),
    (
        "for all intents and purposes",
        "`in practice`, or omit if unnecessary",
    ),
    ("for the duration of", "`during` or `throughout`"),
    (
        "for the purpose of",
        "`to` or `for`; adjust the following verb",
    ),
    ("for the reason that", "`because`"),
    (
        "from my perspective",
        "omit this framing unless the viewpoint matters",
    ),
    ("fully complete", "`complete`"),
    ("fundamental basis", "`basis`"),
    ("furthermore", "`also`"),
    ("give an indication of", "`indicate` or `show`"),
    ("give consideration to", "`consider`"),
    ("given the fact that", "`because` or `since`"),
    ("has a requirement for", "`needs`"),
    ("has the ability to", "`can`"),
    ("has the capability to", "`can`"),
    ("have a requirement for", "`need`"),
    ("have the ability to", "`can`"),
    ("have the capability to", "`can`"),
    ("herein", "`here` or name the location"),
    ("hereinafter", "`from now on` or `below`"),
    ("hitherto", "`so far` or `until now`"),
    ("if this is not the case", "`if not`"),
    ("in a manner that", "`so that`, or use an adverb"),
    ("in a timely manner", "`promptly` or `on time`"),
    ("in accordance with", "`under` or `following`"),
    (
        "in addition to the above",
        "`also`, or omit this transition",
    ),
    ("in advance of", "`before`"),
    (
        "in an effort to",
        "`to` if the attempt itself is not the point",
    ),
    ("in close proximity to", "`near`"),
    ("in conjunction with", "`with`"),
    ("in connection with", "`about` or `for`"),
    ("in light of the fact that", "`because`"),
    (
        "in my opinion",
        "omit this framing unless the distinction from fact matters",
    ),
    ("in order to", "`to`"),
    (
        "in relation to",
        "`about` when no precise relationship is intended",
    ),
    ("in spite of the fact that", "`although`"),
    (
        "in terms of",
        "name the specific relationship, or omit this framing",
    ),
    ("in the absence of", "`without`"),
    ("in the amount of", "`for`, or state the amount directly"),
    ("in the case of", "`for` or `when`"),
    ("in the course of", "`during`"),
    (
        "in the event of",
        "`if there is`; adjust the sentence to fit",
    ),
    ("in the event that", "`if`"),
    (
        "in the final analysis",
        "`ultimately`, or state the conclusion directly",
    ),
    ("in the majority of cases", "`usually`"),
    ("in the near future", "`soon`, or give a specific date"),
    (
        "in the process of",
        "omit this framing if the following verb is enough",
    ),
    ("in view of the fact that", "`because`"),
    ("inasmuch as", "`since` or `because`"),
    ("inception", "`start` or `beginning`"),
    (
        "indeed",
        "omit this emphasis unless it adds a useful contrast",
    ),
    ("is able to", "`can`"),
    ("is capable of", "`can`; adjust the following verb"),
    ("is in a position to", "`can`"),
    ("is indicative of", "`indicates` or `suggests`"),
    ("is of the opinion that", "`thinks`"),
    (
        "it can be seen that",
        "state what the evidence shows directly",
    ),
    (
        "it goes without saying that",
        "omit this opener; state the point directly",
    ),
    (
        "it is apparent that",
        "state the evidence or conclusion directly",
    ),
    (
        "it is clear that",
        "state the evidence or conclusion directly",
    ),
    (
        "it is essential to note that",
        "omit this opener; state the point directly",
    ),
    (
        "it is important to note that",
        "omit this opener; state the point directly",
    ),
    (
        "it is interesting to note that",
        "omit this opener; state the point directly",
    ),
    ("it is necessary to", "`must`; name who must act"),
    (
        "it is worth mentioning that",
        "omit this opener; state the point directly",
    ),
    (
        "it is worth noting that",
        "omit this opener; state the point directly",
    ),
    (
        "it should be emphasized that",
        "omit this opener; state the point directly",
    ),
    (
        "it should be noted that",
        "omit this opener; state the point directly",
    ),
    (
        "it would appear that",
        "`apparently`, or state the evidence with its uncertainty",
    ),
    (
        "it's important to note that",
        "omit this opener; state the point directly",
    ),
    (
        "it's worth mentioning that",
        "omit this opener; state the point directly",
    ),
    (
        "it's worth noting that",
        "omit this opener; state the point directly",
    ),
    (
        "it’s important to note that",
        "omit this opener; state the point directly",
    ),
    (
        "it’s worth mentioning that",
        "omit this opener; state the point directly",
    ),
    (
        "it’s worth noting that",
        "omit this opener; state the point directly",
    ),
    ("last but not least", "`finally`, or omit this transition"),
    (
        "let us delve into",
        "omit this opener; start the explanation",
    ),
    ("let us explore", "omit this opener; start the explanation"),
    (
        "let's delve into",
        "omit this opener; start the explanation",
    ),
    ("let's dive into", "omit this opener; start the explanation"),
    ("let's explore", "omit this opener; start the explanation"),
    (
        "let’s delve into",
        "omit this opener; start the explanation",
    ),
    ("let’s dive into", "omit this opener; start the explanation"),
    ("let’s explore", "omit this opener; start the explanation"),
    (
        "leverage",
        "`use` when no financial or technical meaning is intended",
    ),
    (
        "leveraged",
        "`used` when no financial or technical meaning is intended",
    ),
    (
        "leverages",
        "`uses` when no financial or technical meaning is intended",
    ),
    (
        "leveraging",
        "`using` when no financial or technical meaning is intended",
    ),
    ("make a decision", "`decide`"),
    ("make a determination", "`determine` or `decide`"),
    ("make a modification", "`modify` or `change`"),
    ("make an adjustment", "`adjust`"),
    ("make an attempt", "`try`"),
    ("make use of", "`use`"),
    ("makes use of", "`uses`"),
    ("making use of", "`using`"),
    ("manner in which", "`way`"),
    (
        "methodology",
        "`method` unless the study of methods is meant",
    ),
    ("more often than not", "`usually`"),
    ("moreover", "`also`"),
    ("necessitate", "`need` or `require`"),
    ("necessitates", "`needs` or `requires`"),
    ("nevertheless", "`still` or `even so`"),
    (
        "notwithstanding",
        "`despite` or `still`, depending on grammar",
    ),
    ("numerous", "`many`"),
    ("on a daily basis", "`daily`"),
    ("on a monthly basis", "`monthly`"),
    ("on a regular basis", "`regularly`"),
    ("on a weekly basis", "`weekly`"),
    ("on an annual basis", "`yearly`"),
    ("on the grounds that", "`because`"),
    ("on the occasion of", "`at` or `when`"),
    ("owing to the fact that", "`because`"),
    ("pertaining to", "`about`"),
    ("please be aware that", "state the notice directly"),
    ("please note that", "state the notice directly"),
    (
        "possess",
        "`have` when no specific ownership meaning is intended",
    ),
    ("preplan", "`plan`"),
    ("presently", "`now` or `soon`, depending on meaning"),
    ("prior to", "`before`"),
    ("provided that", "`if`"),
    ("purchase", "`buy` when used as a verb"),
    ("refer back to", "`refer to`"),
    ("regardless of the fact that", "`although` or `even though`"),
    ("remains to be seen", "`is not yet known`"),
    (
        "shall",
        "`must` or `will`, depending on meaning; retain required legal wording",
    ),
    ("should you require", "`if you need`"),
    ("so as to", "`to`"),
    ("subsequent to", "`after`"),
    ("subsequently", "`later` or `then`"),
    ("sufficient", "`enough`"),
    ("sufficiently", "`enough`; adjust word order"),
    ("take into consideration", "`consider`"),
    (
        "terminate",
        "`end` or `stop` unless a precise lifecycle meaning is intended",
    ),
    (
        "the fact of the matter is",
        "omit this opener; state the point directly",
    ),
    ("the question as to whether", "`whether`"),
    (
        "the reason for this is that",
        "`because`; join to the preceding statement",
    ),
    ("there is a need for", "`need`; name who needs it"),
    ("this is a topic that", "`this topic`"),
    ("to a certain extent", "`partly`"),
    ("to be able to", "`to` if ability itself is not the point"),
    (
        "to put it simply",
        "omit this framing; give the simple explanation",
    ),
    ("until such time as", "`until`"),
    ("utilisation", "`use` unless a specific metric is meant"),
    ("utilise", "`use`"),
    ("utilised", "`used`"),
    ("utilises", "`uses`"),
    ("utilising", "`using`"),
    ("utilization", "`use` unless a specific metric is meant"),
    ("utilize", "`use`"),
    ("utilized", "`used`"),
    ("utilizes", "`uses`"),
    ("utilizing", "`using`"),
    ("various different", "`various`"),
    ("whether or not", "`whether` if `or not` adds no meaning"),
    ("whilst", "`while`"),
    ("with a view to", "`to`; adjust the following verb"),
    ("with reference to", "`about`"),
    ("with regard to", "`about`"),
    (
        "with respect to",
        "`about` when no precise relationship is intended",
    ),
    ("with the exception of", "`except`"),
    ("with the intention of", "`to`; adjust the following verb"),
    ("within the realm of", "`in`"),
    (
        "without a doubt",
        "omit this emphasis, or explain the evidence",
    ),
];
