//! `DOC008` - `# Errors` variants listed out of alphabetical order.
//!
//! [`check`] fires when an `# Errors` section lists the returned in-crate
//! enum's declared variants in an order other than alphabetical. Links
//! naming variants the enum does not declare are ignored.

use super::{find_errors_section, is_pub_result_fn, section_body};
use crate::reporting::{Diagnostic, Severity};
use crate::rules::lint::CODE_ERROR_VARIANT_ORDER;
use crate::source::{ParseResult, SourceItem};
use tree_sitter::Node;

/// A top-level enum declaration with its declared variant names.
pub(super) struct DeclaredEnum<'a> {
    /// The enum's name.
    name: &'a str,
    /// Names of the enum's declared variants, in declaration order.
    variants: Vec<&'a str>,
}

/// `DOC008` - `# Errors` variants must be listed in alphabetical order.
///
/// Fires on `pub fn` returning `Result` when all the following hold:
///
/// - a `# Errors` section exists on the item;
/// - the error type's final path segment resolves to a top-level enum in
///   the same file;
/// - the section's `[`Enum::Variant`]` links (short-reference form or
///   crate-root-qualified, e.g. `[`crate::Enum::Variant`]`) list that
///   enum's declared variants in an order that decreases under Rust `str`
///   ordering.
///
/// Links to other enums, prose, unresolved variant names, and non-enum
/// error types never participate.
///
/// # Arguments
///
/// - `item` - the parsed source item to inspect for variant ordering.
/// - `enums` - the file's top-level enums with their declared variants
///   (see [`top_level_enums`]).
pub(super) fn check(item: &SourceItem, enums: &[DeclaredEnum<'_>]) -> Vec<Diagnostic> {
    if !is_pub_result_fn(item) {
        return Vec::new();
    }

    // Same-file resolution: the error type's final segment must name a
    // top-level enum here; everything else is exempt (D3).
    let Some(error_enum) = item.result_error_type() else {
        return Vec::new();
    };
    let Ok(idx) = enums.binary_search_by(|e| e.name.cmp(error_enum)) else {
        return Vec::new();
    };
    let declared = &enums[idx].variants;

    let Some(start) = find_errors_section(item.doc_comments()) else {
        return Vec::new();
    };

    let body = section_body(item.doc_comments(), start);
    let variants: Vec<&str> = body
        .iter()
        .flat_map(|line| linked_variants(line, error_enum, declared))
        .collect();
    if is_non_decreasing(&variants) {
        return Vec::new();
    }

    vec![Diagnostic {
        severity: Severity::Error,
        code: CODE_ERROR_VARIANT_ORDER,
        message: format!("`# Errors` lists variants of `{error_enum}` out of alphabetical order"),
        line: item.start_line(),
        item_kind: item.kind().to_string(),
        item_name: item.name().map(str::to_string),
    }]
}

/// The file's top-level enums with their declared variants, sorted by
/// enum name so resolution can binary-search.
///
/// Root-level `enum_item` nodes are exactly the top-level enums the parse
/// classifies as items; enums nested in modules or generated by macros are
/// never root children. Names borrow from `parsed` (items' source).
pub(super) fn top_level_enums(parsed: &ParseResult) -> Vec<DeclaredEnum<'_>> {
    let bytes = parsed.source.as_bytes();
    let root = parsed.syntax_tree().root_node();

    let mut enums = Vec::new();
    for i in 0..root.named_child_count() as u32 {
        let Some(node) = root.named_child(i) else {
            continue;
        };
        if node.kind() != "enum_item" {
            continue;
        }
        let Some(name) = node
            .child_by_field_name("name")
            .and_then(|n| n.utf8_text(bytes).ok())
        else {
            continue;
        };
        enums.push(DeclaredEnum {
            name,
            variants: declared_variants(node, bytes),
        });
    }

    enums.sort_unstable_by(|a, b| a.name.cmp(b.name));
    enums
}

/// Declared variant names of a top-level `enum_item`, in declaration order.
///
/// Attributes inside the variant list (e.g. `#[doc(hidden)]` on a variant)
/// are not variants and are skipped.
fn declared_variants<'a>(enum_item: Node<'_>, bytes: &'a [u8]) -> Vec<&'a str> {
    let Some(list) = enum_item.child_by_field_name("body") else {
        return Vec::new();
    };

    let mut variants = Vec::new();
    for i in 0..list.named_child_count() as u32 {
        let Some(variant) = list.named_child(i) else {
            continue;
        };
        if variant.kind() != "enum_variant" {
            continue;
        }
        if let Some(name) = variant
            .child_by_field_name("name")
            .and_then(|n| n.utf8_text(bytes).ok())
        {
            variants.push(name);
        }
    }
    variants
}

/// True when `variants` never decreases under Rust `str` ordering.
fn is_non_decreasing(variants: &[&str]) -> bool {
    variants.windows(2).all(|pair| pair[0] <= pair[1])
}

/// Variants of `enum_name` linked on `line`, in document order.
///
/// A participating link is a bracketed `[`Enum::Variant`]` reference
/// (crate-root prefixes like `[`crate::Enum::Variant`]` allowed) whose
/// second-to-last `::` segment is `enum_name`. The variant must also be
/// one of `declared`.
///
/// Excluded links:
///
/// - foreign qualified paths (`io::Error::V`), even when the enum name
///   collides;
/// - bracket contents without a `::` path;
/// - variant names the enum does not declare (unresolved links).
fn linked_variants<'a>(
    line: &'a str,
    enum_name: &'a str,
    declared: &'a [&str],
) -> impl Iterator<Item = &'a str> + 'a {
    line.split(']').filter_map(move |chunk| {
        let inner = chunk.rsplit_once('[')?.1;
        link_variant(inner, enum_name, declared)
    })
}

/// The variant named by link content `inner` when it targets `enum_name`
/// and `enum_name` declares that variant.
///
/// Surrounding backticks are trimmed first, so backticked forms like
/// `` [`Enum::Variant`] `` and `` [`path::Enum::Variant`] `` participate
/// like their plain counterparts.
fn link_variant<'a>(inner: &'a str, enum_name: &str, declared: &[&str]) -> Option<&'a str> {
    let inner = inner.trim_matches('`');
    let mut segments = inner.rsplit("::");
    let variant = segments.next()?;
    let linked_enum = segments.next()?;
    // Only unqualified and crate-root-qualified links target a same-file
    // enum; other prefixes (`io::Error::V`) are foreign enums.
    let crate_rooted = matches!(
        segments.next(),
        None | Some("crate") | Some("self") | Some("super")
    );
    // Unresolved links (undeclared variants) never participate.
    (linked_enum == enum_name && crate_rooted && declared.contains(&variant)).then_some(variant)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::languages::rust::parse::parse_source;

    /// Run the DOC008 rule over every item of `source`, as `run_all` does.
    fn lint(source: &str) -> Vec<Diagnostic> {
        let parsed = parse_source(source).unwrap();
        let enums = top_level_enums(&parsed);
        parsed
            .items
            .iter()
            .flat_map(|item| check(item, &enums))
            .collect()
    }

    /// Fixture: an in-crate `Error` enum plus a documented `load` fn whose
    /// `# Errors` body is `errors_body`.
    fn documented_fn(errors_body: &str) -> String {
        format!(
            "/// Doc.\npub enum Error {{ NotFound, Denied }}\n/// Loads.\n///\n/// # Errors\n///\n{errors_body}\npub fn load() -> Result<(), Error> {{ Ok(()) }}\n"
        )
    }

    // ── DOC008: error variant order ──

    // Variants listed out of alphabetical order -> error.
    #[test]
    fn fires_when_variants_out_of_order() {
        let source = documented_fn("/// Returns [Error::NotFound] then [Error::Denied].");
        let diags = lint(&source);
        assert_eq!(diags.len(), 1);
        assert_eq!(diags[0].code, CODE_ERROR_VARIANT_ORDER);
        assert_eq!(diags[0].severity, Severity::Error);
        assert!(diags[0].message.contains("Error"));
    }

    // Alphabetical listing (equal neighbors allowed) -> silent.
    #[test]
    fn silent_when_variants_alphabetical() {
        let source = documented_fn("/// Returns [Error::Denied] then [Error::NotFound].");
        assert!(lint(&source).is_empty());

        // Non-decreasing: a repeated variant does not break the order.
        let source = documented_fn("/// Returns [Error::Denied] then [Error::Denied].");
        assert!(lint(&source).is_empty());
    }

    // Out-of-crate error type (`std::io::Error`) -> exempt even when its
    // final segment collides with no local enum.
    #[test]
    fn silent_when_error_type_out_of_crate() {
        let source = "\
/// Doc.\npub enum Other {{ A, B }}\n\
/// Loads.\n\
///\n/// # Errors\n///\n\
/// Returns [Error::B] then [Error::A].\n\
pub fn load() -> Result<(), std::io::Error> { Ok(()) }}\n";
        assert!(lint(source).is_empty());
    }

    // Out-of-crate error type whose final segment collides with a local
    // enum of the same name -> still exempt (foreign type).
    #[test]
    fn silent_when_out_of_crate_error_type_collides_with_local_enum() {
        let source = concat!(
            "/// Doc.\npub enum Error { NotFound, Denied }\n",
            "/// Loads.\n///\n/// # Errors\n///\n",
            "/// Returns [Error::Denied] then [Error::NotFound].\n",
            "pub fn load() -> Result<(), std::io::Error> { Ok(()) }\n",
        );
        assert!(lint(source).is_empty());
    }

    // Crate-qualified error type from a nested module -> exempt; only a
    // direct crate root can resolve to a same-file top-level enum.
    #[test]
    fn silent_when_error_type_uses_nested_crate_path() {
        let source = concat!(
            "/// Doc.\npub enum Error { NotFound, Denied }\n",
            "/// Loads.\n///\n/// # Errors\n///\n",
            "/// Returns [Error::Denied] then [Error::NotFound].\n",
            "pub fn load() -> Result<(), crate::nested::Error> { Ok(()) }\n",
        );
        assert!(lint(source).is_empty());
    }

    // Qualified links to a foreign enum whose name collides with the
    // returned local enum never participate in the ordering check.
    #[test]
    fn silent_when_foreign_qualified_links_collide_with_local_enum() {
        let source = documented_fn(
            "/// Returns [io::Error::B] then [io::Error::A].\n/// Also [crate::other::Error::B].",
        );
        assert!(lint(&source).is_empty());
    }

    #[test]
    fn check_should_ignore_unresolved_variant_links_when_comparing_order() {
        let cases = [
            ("/// Returns [Error::Zulu] then [Error::Alpha].", 0),
            (
                "/// Returns [Error::Denied], [Error::Zulu], then [Error::NotFound].",
                0,
            ),
            (
                "/// Returns [Error::NotFound], [Error::Zulu], then [Error::Denied].",
                1,
            ),
        ];

        for (errors_body, expected_count) in cases {
            let source = documented_fn(errors_body);

            let diagnostics = lint(&source);

            assert_eq!(diagnostics.len(), expected_count, "{errors_body}");
        }
    }

    // Non-enum error type (a struct) -> exempt.
    #[test]
    fn silent_when_error_type_is_not_an_enum() {
        let source = "\
/// Doc.\npub struct Wrapper;\n\
/// Loads.\n\
///\n/// # Errors\n///\n\
/// Returns [Wrapper::B] then [Wrapper::A].\n\
pub fn load() -> Result<(), Wrapper> { Ok(()) }\n";
        assert!(lint(source).is_empty());
    }

    // Path-qualified links participate like plain ones.
    #[test]
    fn fires_when_path_qualified_links_out_of_order() {
        let source =
            documented_fn("/// Returns [crate::Error::NotFound] then [crate::Error::Denied].");
        assert_eq!(lint(&source).len(), 1);
    }

    // Interleaved prose and links to other enums never participate.
    #[test]
    fn ignores_prose_and_other_enum_links() {
        let source = documented_fn(
            "/// Fails hard sometimes.\n/// See [Other::Z] for context.\n/// Returns [Error::Denied] then [Error::NotFound].",
        );
        // The two participating links are alphabetical -> silent.
        assert!(lint(&source).is_empty());

        let source = documented_fn(
            "/// Returns [Error::NotFound].\n/// See [Other::A] between.\n/// Then [Error::Denied].",
        );
        assert_eq!(lint(&source).len(), 1);
    }

    // Backticked short form participates; out of order -> error.
    #[test]
    fn fires_when_backticked_links_out_of_order() {
        let source = documented_fn("/// Returns [`Error::NotFound`] then [`Error::Denied`].");
        assert_eq!(lint(&source).len(), 1);
    }

    // Backticked and plain links compare by bare variant names.
    #[test]
    fn silent_when_backticked_and_plain_links_alphabetical() {
        let source = documented_fn("/// Returns [`crate::Error::Denied`] then [Error::Denied].");
        assert!(lint(&source).is_empty());
    }

    // No participating links at all -> not applicable.
    #[test]
    fn silent_when_no_variant_links() {
        let source = documented_fn("/// Returns an error if loading fails.");
        assert!(lint(&source).is_empty());
    }
}
